import mongoose from "mongoose";

const RoadmapTopicSchema = new mongoose.Schema({
  title: String,
  description: String,
  resources: [
    {
      type: { type: String, enum: ["video", "docs", "article", "practice"] },
      title: String,
      url: String,
    },
  ],
  estimatedHours: Number,
  priority: { type: String, enum: ["high", "medium", "low"], default: "medium" },
  completed: { type: Boolean, default: false },
});

const RoadmapWeekSchema = new mongoose.Schema({
  week: Number,
  theme: String,
  topics: [RoadmapTopicSchema],
});

const RoadmapSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    interviewId: { type: mongoose.Schema.Types.ObjectId, ref: "InterviewEvaluation" },
    title: { type: String, required: true },
    summary: String,
    estimatedHours: Number,
    weeks: [RoadmapWeekSchema],
    keySkillsToMaster: [String],
    practiceProjects: [String],
    role: String,
    level: String,
    techstack: String,
    overallScore: Number,
    completionPercent: { type: Number, default: 0 },
    isActive: { type: Boolean, default: true },
    autoGenerated: { type: Boolean, default: false },  // true = triggered by low score
    basedOnSessions: { type: Number, default: 1 },      // number of sessions that informed this roadmap
  },
  { timestamps: true }
);

export const Roadmap = mongoose.model("Roadmap", RoadmapSchema);
